# Generated by Django 6.0.5 on 2026-05-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image'),
        ('books', '0003_book_book_id_book_borrowed_count_and_more'),
    ]

    operations = [
    ]
