# Generated by Django 6.0.4 on 2026-05-13 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_merge_20260513_0001'),
        ('users', '0002_book_alter_borrowedbook_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='books.book'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
